version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
