gateway:
  env:
    clientlb:
      enabled: ${ENABLE_CLIENTLB:false}
  mountain:
    host: ${HOST:localhost}
    port: ${PORT:6565}
    enable-ssl: ${ENABLE_SSL:false}

manaslu:
  service:
    parallels: ${PARALLELS:3}
    execution-time: ${EXECUTION_TIME:10s}

# logging
logging:
  level:
    com:
      archetype:
        manaslu: DEBUG
    io:
      grpc: INFO
      netty: INFO
